# 1. What is a Python library? Why ^o we use Python libraries?

# Answer :-
 A Python library is a collection of pre-written code and functions that provide specific functionalities to perform tasks easily without having to write the code from scratch. These libraries are typically created to address common programming tasks or to support specific domains such as web development, data analysis, machine learning, natural language processing, etc.

We use Python libraries for several reasons:

1. **Code Reusability**: Libraries provide pre-implemented functionalities that can be reused in various projects, saving time and effort.

2. **Efficiency**: Libraries are usually written and optimized by experts, so they often offer efficient implementations of algorithms and solutions.

3. **Domain-specific tasks**: Many libraries are tailored to specific tasks or domains, such as scientific computing, data visualization, or web development, providing specialized tools and utilities to handle those tasks effectively.

4. **Community Support**: Popular Python libraries often have large communities of users contributing to their development and maintenance. This means there's a wealth of resources available such as documentation, tutorials, and forums where users can seek help and share knowledge.

5. **Integration**: Python libraries are designed to work seamlessly with other Python code, making it easy to integrate them into your projects.

Overall, Python libraries help developers write better code faster by providing ready-made solutions to common programming challenges.

# 2. What is the ^ifference between Numpy array an^ List?


# Answer :-
NumPy arrays and Python lists are both used to store collections of data, but they have several differences:

1. **Data Types**: 
   - NumPy arrays are homogeneous, meaning all elements in the array must be of the same data type. This allows for more efficient storage and computation.
   - Python lists can contain elements of different data types.

2. **Memory Efficiency**:
   - NumPy arrays typically use less memory than Python lists, especially for large datasets, because NumPy arrays are stored more efficiently in memory.
   
3. **Performance**:
   - NumPy arrays offer better performance for mathematical operations and computations compared to Python lists. This is because NumPy arrays are implemented in C and optimized for performance.
   
4. **Functionality**:
   - NumPy arrays provide a wide range of mathematical functions and operations for array manipulation, such as element-wise operations, linear algebra operations, and statistical functions.
   - Python lists offer more flexibility and a wider range of built-in methods and functions for general-purpose programming tasks.

5. **Indexing and Slicing**:
   - NumPy arrays support advanced indexing and slicing operations, making it easier to work with subsets of data.
   - Python lists also support indexing and slicing but are not as powerful or efficient as NumPy arrays for these operations.

6. **Ease of Use**:
   - Python lists are generally easier to work with for beginners and for general-purpose programming tasks due to their simplicity.
   - NumPy arrays require some knowledge of numerical computing and array manipulation techniques, but they offer more powerful tools for numerical computations and data analysis.

In summary, NumPy arrays are preferred for numerical computing and data manipulation tasks due to their efficiency and functionality, while Python lists are more suitable for general-purpose programming and situations where flexibility is more important than performance.

# 3Find the shape, size and dimension of the following array?
# [[1, 2, 3, 4]
# [5, 6, 7, 8],
# [9, 10, 11, 12]]

In [2]:


import numpy as np

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# Shape
print("Shape:", arr.shape)

# Size
print("Size:", arr.size)

# Dimensions
print("Dimensions:", arr.ndim)


Shape: (3, 4)
Size: 12
Dimensions: 2


# 4. Write python code to access the first row of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [3]:
import numpy as np

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

first_row = arr[0]
print("First Row:", first_row)


First Row: [1 2 3 4]


# 5. How do you access the element at the third row and fourth column from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [4]:
import numpy as np

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

element = arr[2, 3]  # Third row (index 2), fourth column (index 3)
print("Element at third row and fourth column:", element)


Element at third row and fourth column: 12


# 6. Write code to extract all odd-indexed elements from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [5]:
import numpy as np

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

odd_indexed_elements = arr[:, 1::2]  # Slicing: start from index 1, step by 2
print("Odd-indexed elements:")
print(odd_indexed_elements)


Odd-indexed elements:
[[ 2  4]
 [ 6  8]
 [10 12]]


# 7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [6]:
import numpy as np

# Generate random 3x3 matrix with values between 0 and 1
random_matrix = np.random.rand(3, 3)

print("Random 3x3 matrix:")
print(random_matrix)


Random 3x3 matrix:
[[0.32716998 0.58951026 0.59217916]
 [0.99876665 0.63342115 0.00978628]
 [0.65516307 0.15881944 0.39161798]]


# 8. Describe the difference between np.random.rand and np.random.randn?

# Answer :-
The functions `np.random.rand` and `np.random.randn` are both used to generate random numbers with NumPy, but they have some key differences:

1. **Output Distribution**:
   - `np.random.rand`: Generates random numbers from a uniform distribution over the interval [0, 1). This means that each value in the generated array has an equal probability of occurring within this interval.
   - `np.random.randn`: Generates random numbers from a standard normal distribution (also known as Gaussian distribution) with mean 0 and standard deviation 1. In other words, the values are drawn from a bell-shaped curve centered at 0, where values closer to the mean are more likely to occur.

2. **Input Arguments**:
   - `np.random.rand`: Accepts shape parameters as input, which determine the shape of the output array. These shape parameters are provided as separate arguments or as a single tuple.
   - `np.random.randn`: Also accepts shape parameters as input, similar to `np.random.rand`, to specify the shape of the output array.

3. **Usage**:
   - `np.random.rand` is often used when you need random numbers uniformly distributed between 0 and 1, for tasks such as generating random matrices for testing or simulation purposes.
   - `np.random.randn` is commonly used when you need random numbers from a normal distribution, which is frequently encountered in statistical analysis, machine learning, and various scientific simulations.

In summary, `np.random.rand` generates random numbers from a uniform distribution, while `np.random.randn` generates random numbers from a standard normal distribution. The choice between them depends on the specific requirements of your application and the type of random numbers you need.

# 9. Write code to increase the dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [11]:
import numpy as np

# Given array
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# Increase dimension along axis 0
increased_arr = np.expand_dims(arr, axis=0)

print("Original array shape:", arr.shape)
print("Increased array shape:", increased_arr.shape)
print("Increased array:")
print(increased_arr)


Original array shape: (3, 4)
Increased array shape: (1, 3, 4)
Increased array:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


# 10. How to transpose the following array in NumPy?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [12]:
import numpy as np

# Given array
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# Transpose the array using .T attribute
transposed_arr = arr.T

print("Original array:")
print(arr)
print("\nTransposed array using .T attribute:")
print(transposed_arr)

# Transpose the array using np.transpose() function
transposed_arr_np = np.transpose(arr)

print("\nTransposed array using np.transpose() function:")
print(transposed_arr_np)


Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Transposed array using .T attribute:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]

Transposed array using np.transpose() function:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


# 11. Consider the following matrix:
Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Perform the following operation using Python1
# 1. Index wise multiplication

In [17]:
import numpy as np

# Define matrices A2 and B2
A2 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])

B2 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])

# Perform index-wise multiplication
result = np.multiply(A2, B2)

print("Matrix A2:")
print(A2)
print("\nMatrix B2:")
print(B2)
print("\nResult of index-wise multiplication:")
print(result)


Matrix A2:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Matrix B2:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Result of index-wise multiplication:
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]


# 2.  Matrix multiplication

In [18]:
import numpy as np

# Define matrices A and B
A2 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])

B2 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])

# Perform matrix multiplication
result = np.dot(A2, B2.T)  # Alternatively, you can use A2 @ B2.T

print("Matrix A2:")
print(A2)
print("\nMatrix B2:")
print(B2)
print("\nResult of matrix multiplication:")
print(result)


Matrix A2:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Matrix B2:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Result of matrix multiplication:
[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]


# 3. Add both the matrics

In [19]:
import numpy as np

# Define matrices A2 and B2
A2 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])

B2 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])

# Add both matrices
result = A2 + B2

print("Matrix A2:")
print(A2)
print("\nMatrix B2:")
print(B2)
print("\nResult of matrix addition:")
print(result)


Matrix A2:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Matrix B2:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Result of matrix addition:
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


# 4. Subtact matrix B from A

In [20]:
import numpy as np

# Define matrices A and B
A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

B = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

# Subtract matrix B from A
result = A - B

print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)
print("\nResult of subtracting matrix B from A:")
print(result)


Matrix A:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Matrix B:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Result of subtracting matrix B from A:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


# 5. Divide Matrix B by A

In [21]:
import numpy as np

# Define matrices A and B
A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

B = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

# Divide matrix B by A
result = B / A

print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)
print("\nResult of dividing matrix B by A:")
print(result)


Matrix A:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Matrix B:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Result of dividing matrix B by A:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# 12. Which function in Numpy can be used to swap the byte order of an array?

In [13]:
import numpy as np

# Create an array
arr = np.array([1, 2, 3, 4], dtype=np.int32)
print("Original array:", arr)

# Swap byte order
swapped_arr = arr.byteswap()

print("Swapped array:", swapped_arr)


Original array: [1 2 3 4]
Swapped array: [16777216 33554432 50331648 67108864]


# 13. What is the significance of the np.linalg.inv function?

# Answer :-
The `np.linalg.inv` function in NumPy is used to compute the inverse of a square matrix. The significance of this function lies in its application across various mathematical and computational domains:

1. **Solving Linear Systems of Equations**: One of the primary applications of matrix inversion is in solving systems of linear equations. Given a system of equations in matrix form \( Ax = b \), where \( A \) is a square matrix of coefficients, \( x \) is the column vector of unknowns, and \( b \) is the column vector of constants, you can solve for \( x \) by computing the inverse of \( A \) and multiplying it with \( b \): \( x = A^{-1}b \).

2. **Matrix Decompositions and Factorizations**: Matrix inversion is often a part of various matrix decomposition and factorization techniques, such as LU decomposition, QR decomposition, and singular value decomposition (SVD). These techniques are widely used in numerical analysis, statistics, optimization, and machine learning algorithms.

3. **Determinants and Rank**: The inverse of a matrix can provide insights into its properties, such as its determinant and rank. For instance, a square matrix \( A \) is invertible (non-singular) if and only if its determinant \( |A| \) is non-zero. Additionally, the rank of a matrix can be deduced from the rank of its inverse.

4. **Numerical Stability**: In practice, matrix inversion can be numerically unstable, especially for large or ill-conditioned matrices. The `np.linalg.inv` function in NumPy uses efficient algorithms to compute the inverse, taking into account numerical stability considerations.

5. **Applications in Statistics and Probability**: Matrix inversion is fundamental in various statistical and probabilistic computations, such as in multivariate analysis, regression analysis, and Bayesian inference.

Overall, the `np.linalg.inv` function plays a crucial role in linear algebra and its applications across diverse fields, enabling computations involving systems of linear equations, matrix decompositions, determinants, and more. However, it's important to use it judiciously, considering computational efficiency and numerical stability.

# 14. What does the np.reshape function do, and how is it used ?

In [14]:
import numpy as np

# Create a 1D array
arr_1d = np.array([1, 2, 3, 4, 5, 6])

# Reshape the array to a 2x3 matrix
arr_2d = np.reshape(arr_1d, (2, 3))

print("Original array (1D):")
print(arr_1d)
print("\nReshaped array (2D):")
print(arr_2d)


Original array (1D):
[1 2 3 4 5 6]

Reshaped array (2D):
[[1 2 3]
 [4 5 6]]


# 15. What is broadcasting in Numpy?

In [15]:
import numpy as np

# Define two arrays
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr2 = np.array([10, 20, 30])

# Add the arrays
result = arr1 + arr2

print("Array 1:")
print(arr1)
print("\nArray 2:")
print(arr2)
print("\nResult of addition:")
print(result)


Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[10 20 30]

Result of addition:
[[11 22 33]
 [14 25 36]]
